apiVersion: apps/v1
kind: Deployment
metadata:
  name: pharmacies-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pharmacies-service
  template:
    metadata:
      labels:
        app: pharmacies-service
    spec:
      containers:
        - name: pharmacies-container
          image: pharmacies-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4002
---
apiVersion: v1
kind: Service
metadata:
  name: pharmacies-service
spec:
  selector:
    app: pharmacies-service
  type: NodePort
  ports:
    - port: 4002
      targetPort: 4002
      nodePort: 30402
