apiVersion: apps/v1
kind: Deployment
metadata:
  name: addresses-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: addresses-service
  template:
    metadata:
      labels:
        app: addresses-service
    spec:
      containers:
        - name: addresses-container
          image: addresses-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4004
---
apiVersion: v1
kind: Service
metadata:
  name: addresses-service
spec:
  selector:
    app: addresses-service
  type: NodePort
  ports:
    - port: 4004
      targetPort: 4004
      nodePort: 30404
